### PR TITLE
NewId => NewID

### PR DESCRIPTION
**Pull request by sevki**
`Id` is causing the linters to complain when implementing the db interface.
from the go project https://github.com/golang/go/wiki/CodeReviewComments#initialisms
> This rule also applies to "ID" when it is short for "identifier" (which is pretty much all cases when it's not the "id" as in "ego", "superego"), so write "appID" instead of "appId".

### CODE REVIEW

**Comment by cjslep** [comment]
Thanks. Once I get the tags in order, I will add this in the next major version release.

**Comment by cjslep** [comment]
Hey @sevki! I'd like to include this in the v1.0.0 tag release. Mind resolving conflicts and re-submitting for review?

**Comment by sevki** [comment]
done.

**Comment by cjslep** [comment]
Thanks a ton!

**Pull request merged**
