### PR TITLE
Fix #145: Change example domains to standards

### LINKED ISSUE #145: Use example.org instead of example.dev
In https://github.com/go-fed/activity/blob/c7bbac61b652d31589f6744937369164ca36ea59/astool/forgefed.jsonld#L43 the example uses the URL `example.dev`.

It is best-practice to use either `example.com` or `example.org` as these domains are registered / reserved by IANA for exactly the purpose to serve for examples.

(In this case it will not lead to code being executed that invoke that domain, but users of go-fed might do so. If someone registers `example.dev` they might not be benign)

### PR DESCRIPTION
**Pull request by weex**
This is just a search/replace of example.dev to example.org and dev.community to example.com.

### CODE REVIEW

**Comment by weex** [comment]
If the two example domains aren't needed, let me know and I'll switch the .coms to .org

**Review by cjslep — APPROVED** [review]
Thanks for doing this! Apologies for the delayed review. I believe I may have pulled these examples from the ForgeFed spec -- you may want to submit a similar change to them if you have not already!

**Comment by weex** [comment]
@cjslep Do you have a link to the ForgeFed spec? I'll update there but haven't been able to find it.

**Comment by cjslep** [comment]
These are what I have bookmarked, I hope they help:

* https://forgefed.peers.community/
* https://notabug.org/peers/forgefed

**Pull request merged**
